# -*- coding: utf-8 -*-
"""UNetScoreNetipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cM7JpLe6TydD-HRio-DHA7k9cF6xQl9q
"""

!pip install torch torchvision matplotlib tqdm
!python ncsn_mnist.py

import math
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
from torchvision import datasets, transforms
from torch.utils.data import DataLoader


class SinusoidalPositionEmbeddings(nn.Module):
    """ Синусоидальные эмбеддинги уровней шума """
    def __init__(self, dim):
        super().__init__()
        self.dim = dim

    def forward(self, time):
        device = time.device
        half_dim = self.dim // 2
        embeddings = math.log(10000) / (half_dim - 1)
        embeddings = torch.exp(torch.arange(half_dim, device=device) * -embeddings)
        embeddings = time[:, None] * embeddings[None, :]
        embeddings = torch.cat((embeddings.sin(), embeddings.cos()), dim=-1)
        return embeddings

class Block(nn.Module):
    """ Базовый блок свёртки с групповой нормализацией """
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.conv = nn.Conv2d(in_ch, out_ch, 3, padding=1)
        self.norm = nn.GroupNorm(4, out_ch)
        self.act = nn.SiLU()

    def forward(self, x):
        return self.act(self.norm(self.conv(x)))

class ResnetBlock(nn.Module):
    """ Остаточный блок с подмешиванием эмбеддинга шума """
    def __init__(self, in_ch, out_ch, noise_emb_dim):
        super().__init__()
        self.noise_mlp = nn.Sequential(nn.SiLU(), nn.Linear(noise_emb_dim, out_ch))
        self.block1 = Block(in_ch, out_ch)
        self.block2 = Block(out_ch, out_ch)
        self.res_conv = nn.Conv2d(in_ch, out_ch, 1) if in_ch != out_ch else nn.Identity()

    def forward(self, x, noise_emb):
        h = self.block1(x)
        h = h + self.noise_mlp(noise_emb).view(-1, h.shape[1], 1, 1)
        h = self.block2(h)
        return h + self.res_conv(x)

class AdvancedUNetScoreNet(nn.Module):
    """ Score-network архитектура U-Net """
    def __init__(self, dim=32):
        super().__init__()
        self.noise_mlp = nn.Sequential(
            SinusoidalPositionEmbeddings(dim),
            nn.Linear(dim, dim * 4),
            nn.GELU(),
            nn.Linear(dim * 4, dim * 4)
        )

        # Encoder
        self.init_conv = nn.Conv2d(1, dim, 3, padding=1)
        self.down1 = ResnetBlock(dim, dim, dim * 4)
        self.pool1 = nn.Conv2d(dim, dim, 4, stride=2, padding=1) # 14x14

        self.down2 = ResnetBlock(dim, dim * 2, dim * 4)
        self.pool2 = nn.Conv2d(dim * 2, dim * 2, 4, stride=2, padding=1) # 7x7

        # Bottleneck
        self.mid1 = ResnetBlock(dim * 2, dim * 2, dim * 4)
        self.mid2 = ResnetBlock(dim * 2, dim * 2, dim * 4)

        # Decoder
        self.up1 = nn.ConvTranspose2d(dim * 2, dim * 2, 4, stride=2, padding=1) # 14x14
        self.up_block1 = ResnetBlock(dim * 4, dim, dim * 4)

        self.up2 = nn.ConvTranspose2d(dim, dim, 4, stride=2, padding=1) # 28x28
        self.up_block2 = ResnetBlock(dim * 2, dim, dim * 4)

        self.final_conv = nn.Conv2d(dim, 1, 1)

    def forward(self, x, sigma_idx, sigmas):
        t_emb = self.noise_mlp(sigma_idx.float())

        x1 = self.init_conv(x)
        x1 = self.down1(x1, t_emb)
        x2 = self.pool1(x1)
        x2 = self.down2(x2, t_emb)
        x3 = self.pool2(x2)


        x3 = self.mid1(x3, t_emb)
        x3 = self.mid2(x3, t_emb)


        x_up = self.up1(x3)
        x_up = torch.cat((x_up, x2), dim=1)
        x_up = self.up_block1(x_up, t_emb)

        x_up = self.up2(x_up)
        x_up = torch.cat((x_up, x1), dim=1)
        x_up = self.up_block2(x_up, t_emb)

        score = self.final_conv(x_up)

        sigma_scaled = sigmas[sigma_idx].view(-1, 1, 1, 1)
        return score / sigma_scaled




device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Параметры геом прогрессии шумов
L = 50
sigma_1 = 1.0
sigma_L = 0.01
sigmas = torch.tensor(np.exp(np.linspace(np.log(sigma_1), np.log(sigma_L), L)), dtype=torch.float32).to(device)

model = AdvancedUNetScoreNet(dim=32).to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=5e-4, weight_decay=1e-4)

def loss_fn(model, x, sigmas):
    batch_size = x.size(0)

    sigma_idx = torch.randint(0, len(sigmas), (batch_size,), device=x.device)
    sigma_scaled = sigmas[sigma_idx].view(batch_size, 1, 1, 1)

    noise = torch.randn_like(x)
    x_tilda = x + sigma_scaled * noise

    score = model(x_tilda, sigma_idx, sigmas)

    loss = 0.5 * torch.mean((sigma_scaled * score + noise) ** 2)
    return loss




transform = transforms.Compose([transforms.ToTensor()])
dataset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
dataloader = DataLoader(dataset, batch_size=128, shuffle=True, drop_last=True)

epochs = 15
print(f"Старт обучения модели на устройстве: {device}")

for epoch in range(epochs):
    model.train()
    total_loss = 0
    for x, _ in dataloader:
        x = x.to(device)

        optimizer.zero_grad()
        loss = loss_fn(model, x, sigmas)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}/{epochs} | Loss: {total_loss / len(dataloader):.5f}")



@torch.no_grad()
def sample_langevin(model, sigmas, img_shape=(1, 28, 28), num_samples=16, T=30, eps=4e-5):
    model.eval()

    x = torch.randn((num_samples, *img_shape), device=sigmas.device)

    for i in range(len(sigmas)):
        sigma_i = sigmas[i]
        alpha_i = eps * (sigma_i ** 2) / (sigmas[-1] ** 2)

        for t in range(T):
            if i == len(sigmas) - 1 and t == T - 1:
                z = torch.zeros_like(x)
            else:
                z = torch.randn_like(x)

            sigma_idx = torch.full((num_samples,), i, dtype=torch.long, device=sigmas.device)

            score = model(x, sigma_idx, sigmas)

            x = x + 0.5 * alpha_i * score + torch.sqrt(alpha_i) * z

    return torch.clamp(x, 0.0, 1.0)


samples = sample_langevin(model, sigmas, num_samples=16, T=30, eps=3e-5)
samples = samples.cpu().numpy()

fig, axes = plt.subplots(4, 4, figsize=(6, 6))
for i, ax in enumerate(axes.flatten()):
    binary_img = samples[i, 0] > 0.4

    ax.imshow(binary_img, cmap='gray')
    ax.axis('off')

plt.tight_layout()
plt.show()